apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-machine
  name: cert-machine
  namespace: cert-machine
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cert-machine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cert-machine
      annotations:
        checksum/secrets: cert-ca | sha256sum
    spec:
      containers:
      - image: eumel8/cert-machine:latest
        imagePullPolicy: Always
        name: cert-machine
        ports:
          - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          runAsNonRoot: true
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: APP
          value: "cert-machine"
        - name: ca_key_password
          valueFrom:
            secretKeyRef:
              name: ca-key-password
              key: ca_key_password
        volumeMounts:
          - name: cert-ca
            mountPath: "/certs"
            readOnly: true
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cert-ca
          secret:
            secretName: cert-ca
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
